"""update_unidad_contenido_soft_delete_fields

Revision ID: 7112d07b7942
Revises: b11bc5f7e4d4
Create Date: 2026-01-02 18:26:21.317324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7112d07b7942'
down_revision: Union[str, Sequence[str], None] = 'b11bc5f7e4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Categoria', 'eliminado',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    
    # 🔥 AJUSTE: Agregar server_default='0' para registros existentes
    op.add_column('Unidad_Contenido', sa.Column(
        'eliminado', 
        sa.Boolean(), 
        nullable=False, 
        server_default='0',  # ← IMPORTANTE: Para registros existentes
        comment='Indica si el contenido fue eliminado lógicamente'
    ))
    
    op.add_column('Unidad_Contenido', sa.Column(
        'fecha_eliminacion', 
        sa.DateTime(), 
        nullable=True, 
        comment='Fecha y hora de eliminación'
    ))
    
    op.add_column('Unidad_Contenido', sa.Column(
        'eliminado_por', 
        sa.Integer(), 
        nullable=True, 
        comment='Usuario que eliminó el contenido'
    ))
    
    # 🔥 AJUSTE: Solo crear un índice (eliminar el duplicado)
    op.create_index('idx_eliminado', 'Unidad_Contenido', ['eliminado'], unique=False)
    
    # 🔥 AJUSTE: Dar nombre explícito al foreign key
    op.create_foreign_key(
        'fk_unidad_contenido_eliminado_por',  # Nombre explícito
        'Unidad_Contenido', 
        'Usuario', 
        ['eliminado_por'], 
        ['id_usuario'], 
        ondelete='SET NULL'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 🔥 AJUSTE: Usar el nombre explícito del foreign key
    op.drop_constraint('fk_unidad_contenido_eliminado_por', 'Unidad_Contenido', type_='foreignkey')
    
    # 🔥 AJUSTE: Solo eliminar el índice que creamos
    op.drop_index('idx_eliminado', table_name='Unidad_Contenido')
    
    op.drop_column('Unidad_Contenido', 'eliminado_por')
    op.drop_column('Unidad_Contenido', 'fecha_eliminacion')
    op.drop_column('Unidad_Contenido', 'eliminado')
    
    op.alter_column('Categoria', 'eliminado',
            existing_type=mysql.TINYINT(display_width=1),
            nullable=False,
            existing_server_default=sa.text('0'))
    # ### end Alembic commands ###