"""agregar_campo_eliminado_a_categoria

Revision ID: b11bc5f7e4d4
Revises: 
Create Date: 2026-01-01 21:31:34.986248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11bc5f7e4d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Agregar columna como nullable primero
    op.add_column('Categoria', sa.Column('eliminado', sa.Boolean(), nullable=True))
    
    # 2. ✅ Actualizar registros existentes con valor por defecto FALSE
    op.execute("UPDATE Categoria SET eliminado = FALSE WHERE eliminado IS NULL")
    
    # 3. ✅ Hacer el campo NOT NULL después de actualizar los datos
    op.alter_column('Categoria', 'eliminado',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default='0')
    
    # 4. Crear índice
    op.create_index(op.f('ix_Categoria_eliminado'), 'Categoria', ['eliminado'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Categoria_eliminado'), table_name='Categoria')
    op.drop_column('Categoria', 'eliminado')
    # ### end Alembic commands ###